name: build-main
run-name: ${{ github.actor }} 
on:
  push:
    branches: 
      - main

env:
  GALASACTL_VERSION: "0.31.0"
  MAVEN_CENTRAL_URL: https://repo.maven.apache.org/maven2

jobs:

  build-and-publish-to-github-maven:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build and publish maven packages
        run: mvn --batch-mode --update-snapshots deploy -D
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  run-galasa-tests:
    runs-on: ubuntu-latest
    needs: build-and-publish-to-github-maven
    steps:

      - name: which version of galasactl are we using
        uses: techcobweb/galasactl-action@v1
        with:
          galasactl_version: ${{env.GALASACTL_VERSION}}
          galasactl_args: --version

      - name: run simple test
        uses: techcobweb/galasactl-action@v1
        with:
          galasactl_version: ${{env.GALASACTL_VERSION}}
          galasactl_args: |
            runs submit local \
            --obr mvn:dev.galasa.example.banking/dev.galasa.example.banking.payee/0.0.1-SNAPSHOT \
            --obr mvn:dev.galasa.example.banking/dev.galasa.example.banking.account/0.0.1-SNAPSHOT \
            --class dev.galasa.example.banking.payee/dev.galasa.example.banking.payee.TestPayee \
            --class dev.galasa.example.banking.payee/dev.galasa.example.banking.account.TestAccount \
            --remoteMaven ${{env.MAVEN_CENTRAL_URL}} \
            --throttle 1 \
            --log -



  # galasactl-version-job:
  #   runs-on: ubuntu-latest
  #   needs: build-and-publish-to-github-maven
  #   name: invoke galasactl
  #   steps:
  #     - name: which version of galasactl are we using
  #       id: galasactl-version
  #       uses: addnab/docker-run-action@v3
  #       with:
  #         image: icr.io/galasadev/galasa-cli-amd64:${{env.GALASACTL_VERSION}}
  #         run: |
  #           galasactl --version

  #     - name: run the tests we compiled earlier
  #       id: run-galasa-tests
  #       uses: addnab/docker-run-action@v3
  #       with:
  #         image: icr.io/galasadev/galasa-cli-amd64:${{env.GALASACTL_VERSION}}
  #         options: -v ${{ github.workspace }}:/
  #         run: |
  #           galasactl runs submit local \
  #           --obr mvn:dev.galasa.example.banking/dev.galasa.example.banking.payee/0.0.1-SNAPSHOT \
  #           --obr mvn:dev.galasa.example.banking/dev.galasa.example.banking.account/0.0.1-SNAPSHOT \
  #           --class dev.galasa.example.banking.payee/dev.galasa.example.banking.payee.TestPayee \
  #           --class dev.galasa.example.banking.payee/dev.galasa.example.banking.account.TestAccount \
  #           --remoteMaven ${{env.MAVEN_CENTRAL_URL}} \
  #           --localMaven 
  #           --throttle 1 \
  #           --log -

