name: build
run-name: ${{ github.actor }} 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout the code
          uses: actions/checkout@v4

        - name: Set up JDK 11
          uses: actions/setup-java@v3
          with:
            java-version: '11'
            distribution: 'temurin'
            cache: maven

        - name: Build with Maven
          run: mvn --batch-mode --update-snapshots verify
        
        - name: Upload build artifacts
          uses: actions/upload-artifact@v3
          with:
            name: Package
            path: staging

        - name: Run galasa tests locally
          uses: techcobweb/galasactl-action@v0.30.0
          with:
            galasactl-args: |
              - runs
              - local
              - --obr dev.galasa.example.banking.obr
              - --obr mvn:dev.galasa.example.banking/dev.galasa.example.banking/0.0.1-SNAPSHOT/obr
              - --class dev.galasa.example.banking.account/dev.galasa.example.banking.account.TestAccount
              - --class dev.galasa.example.banking.account/dev.galasa.example.banking.account.TestAccountExtended
              - --class dev.galasa.example.banking.payee/dev.galasa.example.banking.payee.TestPayee
              - --class dev.galasa.example.banking.payee/dev.galasa.example.banking.payee.TestPayeeExtended
              - --throttle 1
              - --requesttype MikeCLI
              - --poll 10
              - --progress 1
              - --log -
          env:
            GALASA_HOME: home