name: build
run-name: ${{ github.actor }} 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Setup java 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging
      
      # - name: Upload build artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: Package
      #     path: staging



  # test:
  #   runs-on: gh.io/techcobweb/galasactl-image
    
  #   steps:
  #     - name: Checkout the code
  #       uses: actions/checkout@v4

  #     - name: Run galasa tests locally
  #       uses: techcobweb/galasactl-action@v0.30.0
    
  #       with:
  #         galasactl-args: |
  #           runs
  #           submit
  #           local
  #           --obr dev.galasa.example.banking.obr
  #           --obr mvn:dev.galasa.example.banking/dev.galasa.example.banking/0.0.1-SNAPSHOT/obr
  #           --class dev.galasa.example.banking.account/dev.galasa.example.banking.account.TestAccount
  #           --class dev.galasa.example.banking.account/dev.galasa.example.banking.account.TestAccountExtended
  #           --class dev.galasa.example.banking.payee/dev.galasa.example.banking.payee.TestPayee
  #           --class dev.galasa.example.banking.payee/dev.galasa.example.banking.payee.TestPayeeExtended
  #           --throttle 1
  #           --requesttype MikeCLI
  #           --poll 10
  #           --progress 1
  #           --log -
  #           --galasahome /mnt/home
      

            