name: build-main
run-name: ${{ github.actor }} 
on:
  push:
    branches: 
      - main

env:
  GALASACTL_VERSION: "0.31.0"

jobs:

  # build-and-publish-to-github-maven:
  #   runs-on: ubuntu-latest
    
  #   permissions:
  #     contents: read
  #     packages: write
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-java@v4
  #       with:
  #         java-version: '11'
  #         distribution: 'temurin'
  #     - name: Build and publish maven packages
  #       run: mvn --batch-mode --update-snapshots deploy
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  galasactl-version-job:
    runs-on: ubuntu-latest
     
    # needs: build-and-publish-to-github-maven

    name: invoke galasactl
    steps:
      - name: which version of galasactl are we using
        id: galasacrl-version
        uses: addnab/docker-run-action@v3
        with:
          image: icr.io/galasadev/galasa-cli-amd64:${{env.GALASACTL_VERSION}}
          run: |
            galasactl --version